extraction:
  cpp:
    after_prepare: 
      - python report.py 86
  cobol:
    after_prepare: 
      - python report.py 86
  csharp:
    after_prepare: 
      - python report.py 86
  java:
    after_prepare: 
      - python report.py 86
  javascript:
    after_prepare: 
      - python report.py 86
  python:
    after_prepare: 
      - python report.py 86
